### ISSUE TITLE
Problem with cartogram / nuts0

### ISSUE THREAD

**Issue by nelsonmau** [Dataninja/drawmaps#3]
cartogram does not work with the following data

Id | Country | Cases
-- | -- | --
AL | Albania | 14266
AD | Andorra | 2110
AT | Austria | 48146
BY | Belarus | 79852
BE | Belgium | 130235
BA | Bosnia and Herzegovina | 28354
BG | Bulgaria | 21587
HR | Croatia | 17659
CY | Cyprus | 1824
CZ | Czechia | 82446
DK | Denmark | 30168
EE | Estonia | 3607
FI | Finland | 10538
FR | France | 629509
DE | Germany | 301573
GR | Greece | 19842
HU | Hungary | 30575
IS | Iceland | 2921
IE | Ireland | 38032
IT | Italy | 325329
XK | Kosovo | 12683
LV | Latvia | 2086
LI | Liechtenstein | 126
LT | Lithuania | 5185
LU | Luxembourg | 8709
MT | Malta | 3270
MD | Moldova | 56579
MC | Monaco | 222
ME | Montenegro | 12127
NL | Netherlands | 141226
NO | Norway | 14457
PL | Poland | 100074
PT | Portugal | 79151
MK | North Macedonia | 18790
RO | Romania | 135900
RU | Russia | 1209039
SM | San Marino | 732
RS | Serbia | 33901
SK | Slovakia | 13139
SI | Slovenia | 6498
ES | Spain | 789932
SE | Sweden | 94283
CH | Switzerland | 54384
UA | Ukraine | 232424
GB | United Kingdom | 505619
VA | Vatican City | 12

**Comment by jenkin** [comment]
No, it works very well, see the image below generated using your data... you need to map `Id` to `Area` and `Cases` to `Size` and then choose `europe-nuts0` shapefile.

![issue-3](https://user-images.githubusercontent.com/426495/95104576-460fc880-0736-11eb-8c72-36ff13fd6f73.png)
